### ISSUE TITLE
Task Administration: create_task()

### ISSUE THREAD

**Issue by l0renor** [l0renor/kernel#2]
![grafik](https://user-images.githubusercontent.com/32636100/51932780-29b77680-2400-11e9-9434-9bfbd43eb457.png)

**Comment by freinold** [comment]
Had to write helper function _static void add_to_list_

**Comment by freinold** [comment]
Done for the first, but there are some things missing which weren't in the pseudo-code

**Comment by l0renor** [comment]
Not tested for running kernel, only for startup mode
